/**
 * User: Vincent DOBA
 * Date: 28/05/11
 * Time: 20:50
 */

/**
 * === Problem n°2 ===
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 */

def problem2(sum:BigInt, f1:BigInt, f2:BigInt):BigInt ={
  if (f1>4000000)
    sum
  else if (f1%2 == 0)
    problem2(sum + f1, f2, f1 + f2)
  else
    problem2(sum, f2, f1 + f2)
}

println(problem2(0, 1, 1))

// Answer is 4613732